---
- hosts: all
  become: yes

  tasks:
  - name: create a group
    group:
      name: Devops
      state: present

  - name: Create a user
    user:
      name: systoker
      group: Devops 
      password: "{{ 'password' | password_hash('sha512') }}"
      state: present
