---
- hosts: all
  become: yes

  tasks:
  - name: Ensure NTP is installed
    ansible.builtin.yum:
      name: ntp
      state: present

  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: ntpd
      state: started
